### ISSUE TITLE
HotSwapAgent plugin for IntelliJ IDEA

### ISSUE THREAD

**Issue by hibissscus** [HotswapProjects/HotswapAgentPages#2]
Hi there! Thank you very mach for your work! You did really good stuff. I wonder if it's possible to update slightly some pages on http://hotswapagent.org/mydoc_setup_intellij_idea.html and add link to https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin (this plugin intends to simplify the usage of HotSwapAgent inside IntelliJ IDEA) Thank you in advance. 

https://plugins.jetbrains.com/plugin/9552-hotswapagent
![image](https://cloud.githubusercontent.com/assets/1389501/24543737/f5bf8944-1600-11e7-9201-5594302153ad.png)

**Comment by skybber** [comment]
Hi, thank you for feedback and great work. We're missing IDE plugins a lot! You can update IntelliIdea doc at https://github.com/HotswapProjects/HotswapAgentPages/blob/master/pages/mydoc/mydoc_setup_intellij_idea.md , othwerwise we'll do that according your instruction .

**Comment by hibissscus** [comment]
Hi, thank you for the quick answer.

I will do today a pull request to your repo with plugin description.

Best regards,
Sergei
