### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by ghost** [HotswapProjects/HotswapAgentPages#22]
Most of the web is encrypted via HTTPS (TLS/SSL) today.
If deploying onto GitHub pages, check CNAME and GitHub settings to enable HTTPS.
If self-hosting, see [Let's Encrypt](https://letsencrypt.org/) and [CertBot](https://certbot.eff.org/) for free and automatically-renewed certs.

**Comment by skybber** [comment]
fixed, thanks for report!
